public class CreateCarData {
    
    public static void createPackageData(){
        
        Account acc = new Account(Name='Autumn Motors');
        insert acc;
        
        /*
        List<Car_Type__c> carTypes = new List<Car_Type__c>();
        Car_Type__c carType1 = new Car_Type__c(Name='Exotic');
        Car_Type__c carType2 = new Car_Type__c(Name='Sports');
        Car_Type__c carType3 = new Car_Type__c(Name='Luxury');
        Car_Type__c carType4 = new Car_Type__c(Name='SUV');
        carTypes.add(carType1);
        carTypes.add(carType2);
        carTypes.add(carType3);
        carTypes.add(carType4);
        insert carTypes;
        
        
        List<Car__c> cars = new List<Car__c>();
        Car__c car1 = new Car__c(Name='Ferrari Portofino', Car_Type__c=carType1.id,
                                Year__c=2021, Description__c='The Ferrari Portofino (Type F164) is a grand touring sports car produced by the Italian automotive manufacturer Ferrari and has a 0–60 mph (0–97 km/h) time of 3.5 seconds.', Test_Drive__c=true, 
                                Mileage__c=0, Price__c=175000,
                                Picture__c='https://en.wikipedia.org/wiki/Ferrari_Portofino#/media/File:Ferrari_Portofino_M_IMG_4351.jpg');
        Car__c car1 = new Car__c(Name='Cadillac CT5', Car_Type__c=carType3.id,
                                Year__c=2022, Description__c='Discover the 2022 CT5 Mid-Size Sedan built with luxurious amenities inside, sophisticated craftsmanship on the outside, & a suite of advanced safety.', Test_Drive__c=true, 
                                Mileage__c=0, Price__c=87985,
                                Picture__c='https://images.unsplash.com/photo-1589148938909-4d241c91ee52?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80');
        cars.add(car1);
        cars.add(car2);
      
        insert cars;

        */
        
    }

}